### ISSUE TITLE
consider adding your scripts to generate the gh-pages in the master branch 

### ISSUE THREAD

**Issue by LaurentGoderre** [SFMOCI/openlaw#1]
This would allow another city to re purpose the project.

**Comment by jasonlally** [comment]
Can you elaborate? Not using any scripts to generate the page on gh-pages, just straight HTML, CSS and javascript.  Cities that fork the project can reuse the code on the gh-pages branch.

**Comment by LaurentGoderre** [comment]
You don't use a script to convert the text or rdf to html? How do they stay in sync?

**Comment by seanknox** [comment]
@LaurentGoderre The website just links to the zip files in the repo (I'd assume). There's nothing dynamic.

**Comment by LaurentGoderre** [comment]
So the laws are not in a Web format?

**Comment by seanknox** [comment]
The laws are in TXT and RTF format, compressed in a zip or tar.gz file.

**Comment by jasonlally** [comment]
The text files are being parsed separately and fed in to http://sanfranciscocode.org.  Here they are available as JSON bulk downloads or via an API.

**Comment by jasonlally** [comment]
Once we kick the tires on the parsers, I'll share those here and in the documentation.

**Comment by jasonlally** [comment]
Here are the parsers: https://github.com/opengovfoundation/sf-parsers
