### ISSUE TITLE
consider converting the character encoding to UTF8 

### ISSUE THREAD

**Issue by LaurentGoderre** [SFMOCI/openlaw#2]
There appears to be some character encoding issues in some of the .txt files that would probably get fixed by switching to utf8. Further more it would allow to support other languages (such as Spanish) more easily

**Comment by jasonlally** [comment]
Good point. I'll work on this.

**Comment by seanknox** [comment]
Submitted a PR for this: https://github.com/SFMOCI/openlaw/pull/4
